// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as `api <area> <action>`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output).
import { Command } from 'commander';
import { callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = [
 {
  "area": "api-keys",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/api-keys",
    "summary": "Create an API key.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/api-keys/{id}",
    "summary": "Revoke an API key: requests with it get 401 from now on.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/api-keys",
    "summary": "List the workspace's active API keys (newest first).",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "audit",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/audit",
    "summary": "List audit",
    "pathParams": [],
    "query": [
     {
      "name": "action",
      "kind": "string",
      "required": false
     },
     {
      "name": "actor",
      "kind": "string",
      "required": false
     },
     {
      "name": "q",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "billing",
  "routes": [
   {
    "name": "checkout",
    "method": "POST",
    "path": "/api/v1/billing/checkout",
    "summary": "POST /checkout {tier} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "tier",
      "kind": "string",
      "required": true,
      "choices": [
       "free",
       "starter",
       "growth",
       "business"
      ]
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/billing",
    "summary": "Current subscription (free default) + the tier table.",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "ci",
  "routes": [
   {
    "name": "lint",
    "method": "POST",
    "path": "/api/v1/ci/lint",
    "summary": "Create a lint",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "configText",
      "kind": "string",
      "required": true
     }
    ]
   }
  ]
 },
 {
  "area": "jobs",
  "routes": [
   {
    "name": "artifacts-download",
    "method": "GET",
    "path": "/api/v1/jobs/{id}/artifacts/{artId}/download",
    "summary": "List download",
    "pathParams": [
     "id",
     "artId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "cancel",
    "method": "POST",
    "path": "/api/v1/jobs/{id}/cancel",
    "summary": "Cancel a job",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/jobs/{id}",
    "summary": "Get a job",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "log",
    "method": "GET",
    "path": "/api/v1/jobs/{id}/log",
    "summary": "List log",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "from",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "log-stream",
    "method": "GET",
    "path": "/api/v1/jobs/{id}/log/stream",
    "summary": "SSE tail: replays chunks from ?from= then polls the DB every ~1s.",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "from",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "play",
    "method": "POST",
    "path": "/api/v1/jobs/{id}/play",
    "summary": "Play a job",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "retry",
    "method": "POST",
    "path": "/api/v1/jobs/{id}/retry",
    "summary": "Retry a job",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "pipelines",
  "routes": [
   {
    "name": "cancel",
    "method": "POST",
    "path": "/api/v1/pipelines/{id}/cancel",
    "summary": "Cancel a pipeline",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/pipelines/{id}",
    "summary": "Get a pipeline",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "retry",
    "method": "POST",
    "path": "/api/v1/pipelines/{id}/retry",
    "summary": "Retry a pipeline",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "projects",
  "routes": [
   {
    "name": "config",
    "method": "GET",
    "path": "/api/v1/projects/{id}/config",
    "summary": "List config",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/projects",
    "summary": "Create a project",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "repoFullName",
      "kind": "string",
      "required": true
     },
     {
      "name": "defaultBranch",
      "kind": "string",
      "required": false
     },
     {
      "name": "configPath",
      "kind": "string",
      "required": false
     },
     {
      "name": "cloneToken",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create-pipelines",
    "method": "POST",
    "path": "/api/v1/projects/{id}/pipelines",
    "summary": "Pipelines a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "ref",
      "kind": "string",
      "required": true
     },
     {
      "name": "variables",
      "kind": "json",
      "required": false
     }
    ]
   },
   {
    "name": "create-schedules",
    "method": "POST",
    "path": "/api/v1/projects/{id}/schedules",
    "summary": "Schedules a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "cron",
      "kind": "string",
      "required": true
     },
     {
      "name": "ref",
      "kind": "string",
      "required": true
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "variables",
      "kind": "json",
      "required": false
     }
    ]
   },
   {
    "name": "create-variables",
    "method": "POST",
    "path": "/api/v1/projects/{id}/variables",
    "summary": "Variables a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "key",
      "kind": "string",
      "required": true
     },
     {
      "name": "value",
      "kind": "string",
      "required": true
     },
     {
      "name": "backend",
      "kind": "string",
      "required": false,
      "choices": [
       "local",
       "secronna"
      ]
     },
     {
      "name": "masked",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "protected",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "fileType",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/projects/{id}",
    "summary": "Delete a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-schedules",
    "method": "DELETE",
    "path": "/api/v1/projects/{id}/schedules/{schedId}",
    "summary": "Delete a schedule",
    "pathParams": [
     "id",
     "schedId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-variables",
    "method": "DELETE",
    "path": "/api/v1/projects/{id}/variables/{varId}",
    "summary": "Delete a variable",
    "pathParams": [
     "id",
     "varId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/projects/{id}",
    "summary": "Get a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/projects",
    "summary": "List projects",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "pipelines",
    "method": "GET",
    "path": "/api/v1/projects/{id}/pipelines",
    "summary": "List pipelines",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "q",
      "kind": "string",
      "required": false
     },
     {
      "name": "ref",
      "kind": "string",
      "required": false
     },
     {
      "name": "source",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "pipelines-2",
    "method": "GET",
    "path": "/api/v1/projects/{id}/pipelines/{iid}",
    "summary": "Get a pipeline",
    "pathParams": [
     "id",
     "iid"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "pipelines-cancel",
    "method": "POST",
    "path": "/api/v1/projects/{id}/pipelines/{iid}/cancel",
    "summary": "Cancel a pipeline",
    "pathParams": [
     "id",
     "iid"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "pipelines-retry",
    "method": "POST",
    "path": "/api/v1/projects/{id}/pipelines/{iid}/retry",
    "summary": "Retry a pipeline",
    "pathParams": [
     "id",
     "iid"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "schedules",
    "method": "GET",
    "path": "/api/v1/projects/{id}/schedules",
    "summary": "List schedules",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "set-config",
    "method": "PUT",
    "path": "/api/v1/projects/{id}/config",
    "summary": "Config a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "configText",
      "kind": "string",
      "required": true
     },
     {
      "name": "commitMessage",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "update-schedules",
    "method": "PATCH",
    "path": "/api/v1/projects/{id}/schedules/{schedId}",
    "summary": "Update a schedule",
    "pathParams": [
     "id",
     "schedId"
    ],
    "query": [],
    "body": [
     {
      "name": "cron",
      "kind": "string",
      "required": false
     },
     {
      "name": "ref",
      "kind": "string",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "variables",
      "kind": "json",
      "required": false
     }
    ]
   },
   {
    "name": "update-variables",
    "method": "PATCH",
    "path": "/api/v1/projects/{id}/variables/{varId}",
    "summary": "Update a variable",
    "pathParams": [
     "id",
     "varId"
    ],
    "query": [],
    "body": [
     {
      "name": "value",
      "kind": "string",
      "required": false
     },
     {
      "name": "backend",
      "kind": "string",
      "required": false,
      "choices": [
       "local",
       "secronna"
      ]
     },
     {
      "name": "masked",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "protected",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "fileType",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "variables",
    "method": "GET",
    "path": "/api/v1/projects/{id}/variables",
    "summary": "List variables",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "webhook",
    "method": "POST",
    "path": "/api/v1/projects/{id}/webhook",
    "summary": "Idempotent webhook (re)create — the settings page \"re-create\" button.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "public",
  "routes": [
   {
    "name": "badges-pipeline-svg",
    "method": "GET",
    "path": "/api/v1/public/badges/{badgeToken}/pipeline.svg",
    "summary": "List pipeline.svg",
    "pathParams": [
     "badgeToken"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "runners",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/runners",
    "summary": "List runners",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "pause",
    "method": "POST",
    "path": "/api/v1/runners/{id}/pause",
    "summary": "Pause a runner",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "resume",
    "method": "POST",
    "path": "/api/v1/runners/{id}/resume",
    "summary": "Resume a runner",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "schedules",
  "routes": [
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/schedules/{id}",
    "summary": "Delete a schedule",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/schedules",
    "summary": "List schedules",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/schedules/{id}",
    "summary": "Update a schedule",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "cron",
      "kind": "string",
      "required": false
     },
     {
      "name": "ref",
      "kind": "string",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "variables",
      "kind": "json",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "usage",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/usage",
    "summary": "List usage",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 }
];

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? `field-${plain(name)}` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`--${flag(field.name)} must be a number`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(`--${flag(field.name)} must be one of: ${field.choices.join(', ')}`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(`${area} routes`);
    for (const route of routes) {
      const cmd = new Command(route.name).description(`${route.summary} (${route.method} ${route.path})`);
      for (const p of route.pathParams) cmd.argument(`<${p}>`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.choices ? ` (${f.choices.join('|')})` : f.kind === 'json' || f.kind === 'array' ? ` (${f.kind})` : '';
        cmd.option(f.kind === 'boolean' ? `--${flag(f.name)} [value]` : `--${flag(f.name)} <value>`, `${f.required ? 'required' : 'optional'}${hint}`);
      }
      if (route.body) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(`{${p}}`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => `--${flag(f.name)}`);
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd);
    }
    api.addCommand(group);
  }
  return api;
}
